=begin
#smplkit Jobs API

#Scheduled HTTP job execution API for smplkit.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

module SmplkitGeneratedClient::Jobs
  VERSION = '0.0.0'
end
