=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::App
  # One product enrollment as exposed in subscription responses.
  class SubscriptionItemResponse < ApiModelBase
    # Unique identifier for this enrollment.
    attr_accessor :id

    # Product key (e.g. `audit`, `config`, `flags`, `logging`).
    attr_accessor :product

    # Current plan for this product (e.g. `standard`, `pro`).
    attr_accessor :plan

    # Monthly list price for this enrollment, in cents. This value is locked at the time the enrollment was created or last had its plan changed; subsequent changes to the public price list do not affect this enrollment until the customer themselves changes their plan.
    attr_accessor :price_monthly_cents

    # When a plan change is scheduled for the end of the current billing period, this is the plan that will take effect. Otherwise `null`. The value `free` indicates the enrollment will be dropped.
    attr_accessor :pending_plan_change

    # ISO-8601 timestamp at which the pending plan change takes effect. Matches the subscription's `current_period_end`.
    attr_accessor :scheduled_change_effective_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'product' => :'product',
        :'plan' => :'plan',
        :'price_monthly_cents' => :'price_monthly_cents',
        :'pending_plan_change' => :'pending_plan_change',
        :'scheduled_change_effective_at' => :'scheduled_change_effective_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'product' => :'String',
        :'plan' => :'String',
        :'price_monthly_cents' => :'Integer',
        :'pending_plan_change' => :'String',
        :'scheduled_change_effective_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'pending_plan_change',
        :'scheduled_change_effective_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SmplkitGeneratedClient::App::SubscriptionItemResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SmplkitGeneratedClient::App::SubscriptionItemResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'product')
        self.product = attributes[:'product']
      else
        self.product = nil
      end

      if attributes.key?(:'plan')
        self.plan = attributes[:'plan']
      else
        self.plan = nil
      end

      if attributes.key?(:'price_monthly_cents')
        self.price_monthly_cents = attributes[:'price_monthly_cents']
      else
        self.price_monthly_cents = nil
      end

      if attributes.key?(:'pending_plan_change')
        self.pending_plan_change = attributes[:'pending_plan_change']
      end

      if attributes.key?(:'scheduled_change_effective_at')
        self.scheduled_change_effective_at = attributes[:'scheduled_change_effective_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @product.nil?
        invalid_properties.push('invalid value for "product", product cannot be nil.')
      end

      if @plan.nil?
        invalid_properties.push('invalid value for "plan", plan cannot be nil.')
      end

      if @price_monthly_cents.nil?
        invalid_properties.push('invalid value for "price_monthly_cents", price_monthly_cents cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @product.nil?
      return false if @plan.nil?
      return false if @price_monthly_cents.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] product Value to be assigned
    def product=(product)
      if product.nil?
        fail ArgumentError, 'product cannot be nil'
      end

      @product = product
    end

    # Custom attribute writer method with validation
    # @param [Object] plan Value to be assigned
    def plan=(plan)
      if plan.nil?
        fail ArgumentError, 'plan cannot be nil'
      end

      @plan = plan
    end

    # Custom attribute writer method with validation
    # @param [Object] price_monthly_cents Value to be assigned
    def price_monthly_cents=(price_monthly_cents)
      if price_monthly_cents.nil?
        fail ArgumentError, 'price_monthly_cents cannot be nil'
      end

      @price_monthly_cents = price_monthly_cents
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          product == o.product &&
          plan == o.plan &&
          price_monthly_cents == o.price_monthly_cents &&
          pending_plan_change == o.pending_plan_change &&
          scheduled_change_effective_at == o.scheduled_change_effective_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, product, plan, price_monthly_cents, pending_plan_change, scheduled_change_effective_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
