=begin
#smplkit Config API

#Configuration management API for smplkit.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Config::ConfigsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConfigsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Config::ConfigsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConfigsApi' do
    it 'should create an instance of ConfigsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Config::ConfigsApi)
    end
  end

  # unit tests for create_config
  # Create Config
  # Create a config for this account.  The caller supplies the config&#39;s key as &#x60;data.id&#x60;. Keys are unique within an account and immutable for the lifetime of the config.
  # @param config_request 
  # @param [Hash] opts the optional parameters
  # @return [ConfigResponse]
  describe 'create_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_config
  # Delete Config
  # Delete a config by its key.  A config that is referenced as &#x60;parent&#x60; by another config cannot be deleted; reparent or remove the parent reference on every child first. The &#x60;common&#x60; config cannot be deleted.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_config
  # Get Config
  # Retrieve a single config by its key.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ConfigResponse]
  describe 'get_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_configs
  # List Configs
  # List configs for this account.  Default sort is &#x60;key&#x60; ascending. Pass &#x60;filter[parent]&#x3D;&lt;parent_key&gt;&#x60; to return only the direct children of a specific config.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_parent 
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;key&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;key&#x60;, &#x60;-key&#x60;, &#x60;name&#x60;, &#x60;-name&#x60;, &#x60;updated_at&#x60;, &#x60;-updated_at&#x60;.
  # @return [ConfigListResponse]
  describe 'list_configs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_config
  # Update Config
  # Replace a config entirely. Every writable field is overwritten.
  # @param id 
  # @param config_request 
  # @param [Hash] opts the optional parameters
  # @return [ConfigResponse]
  describe 'update_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
