=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SmplkitGeneratedClient::App::Value
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SmplkitGeneratedClient::App::Value do
end
