=begin
#smplkit Logging API

#API for the smplkit logging service.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Logging::LoggerSourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoggerSourcesApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Logging::LoggerSourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoggerSourcesApi' do
    it 'should create an instance of LoggerSourcesApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Logging::LoggerSourcesApi)
    end
  end

  # unit tests for list_all_logger_sources
  # List All Logger Sources
  # List every logger source observation for this account.  Default sort is &#x60;-last_seen&#x60; (most recently observed first). Supports &#x60;filter[environment]&#x60; and &#x60;filter[service]&#x60; to narrow to a specific environment or service.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_environment 
  # @option opts [String] :filter_service 
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-last_seen&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;environment&#x60;, &#x60;-environment&#x60;, &#x60;last_seen&#x60;, &#x60;-last_seen&#x60;, &#x60;service&#x60;, &#x60;-service&#x60;.
  # @return [LoggerSourceListResponse]
  describe 'list_all_logger_sources test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_logger_sources
  # List Logger Sources
  # List the service / environment observations recorded for a logger.  Default sort is &#x60;-last_seen&#x60; (most recently observed first).
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-last_seen&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;environment&#x60;, &#x60;-environment&#x60;, &#x60;last_seen&#x60;, &#x60;-last_seen&#x60;, &#x60;service&#x60;, &#x60;-service&#x60;.
  # @return [LoggerSourceListResponse]
  describe 'list_logger_sources test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
