=begin
#smplkit Logging API

#API for the smplkit logging service.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Logging::ServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServicesApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Logging::ServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicesApi' do
    it 'should create an instance of ServicesApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Logging::ServicesApi)
    end
  end

  # unit tests for list_services
  # List Services
  # List the services that have reported a logger for this account.  Default sort is &#x60;name&#x60; ascending.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;name&#x60;. Allowed values: &#x60;name&#x60;, &#x60;-name&#x60;.
  # @return [ServiceListResponse]
  describe 'list_services test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
