=begin
#smplkit Jobs API

#Scheduled HTTP job execution API for smplkit.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::Jobs
  # Aggregated run statistics for the requested scope.  Computed on demand from the account's runs; `total`, `tally`, `buckets`, and `recent_failures` honor the request's filters, while `next_scheduled` honors only the environment filter (it is forward-looking by definition).
  class RunStat < ApiModelBase
    # Runs matching the filters.
    attr_accessor :total

    # Those runs counted by lifecycle state.
    attr_accessor :tally

    # Run counts over time at the requested `bucket` granularity, ordered by bucket start. Only buckets containing at least one run are listed — treat missing buckets as zero. `null` when the request did not include the `bucket` directive.
    attr_accessor :buckets

    # The most recently created `FAILED` runs matching the filters, newest first — at most 3.
    attr_accessor :recent_failures

    # The soonest `PENDING` run with a fire time at or after the request, or `null` when nothing upcoming is scheduled. The `filter[created_at]` range does not apply here — a run scheduled long ago for a future fire time is still next.
    attr_accessor :next_scheduled

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'total' => :'total',
        :'tally' => :'tally',
        :'buckets' => :'buckets',
        :'recent_failures' => :'recent_failures',
        :'next_scheduled' => :'next_scheduled'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'total' => :'Integer',
        :'tally' => :'RunStatTally',
        :'buckets' => :'Array<RunStatBucket>',
        :'recent_failures' => :'Array<RunStatFailure>',
        :'next_scheduled' => :'RunStatNextScheduled'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'buckets',
        :'next_scheduled'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SmplkitGeneratedClient::Jobs::RunStat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SmplkitGeneratedClient::Jobs::RunStat`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end

      if attributes.key?(:'tally')
        self.tally = attributes[:'tally']
      else
        self.tally = nil
      end

      if attributes.key?(:'buckets')
        if (value = attributes[:'buckets']).is_a?(Array)
          self.buckets = value
        end
      end

      if attributes.key?(:'recent_failures')
        if (value = attributes[:'recent_failures']).is_a?(Array)
          self.recent_failures = value
        end
      else
        self.recent_failures = nil
      end

      if attributes.key?(:'next_scheduled')
        self.next_scheduled = attributes[:'next_scheduled']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      if @tally.nil?
        invalid_properties.push('invalid value for "tally", tally cannot be nil.')
      end

      if @recent_failures.nil?
        invalid_properties.push('invalid value for "recent_failures", recent_failures cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @total.nil?
      return false if @tally.nil?
      return false if @recent_failures.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        fail ArgumentError, 'total cannot be nil'
      end

      @total = total
    end

    # Custom attribute writer method with validation
    # @param [Object] tally Value to be assigned
    def tally=(tally)
      if tally.nil?
        fail ArgumentError, 'tally cannot be nil'
      end

      @tally = tally
    end

    # Custom attribute writer method with validation
    # @param [Object] recent_failures Value to be assigned
    def recent_failures=(recent_failures)
      if recent_failures.nil?
        fail ArgumentError, 'recent_failures cannot be nil'
      end

      @recent_failures = recent_failures
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          total == o.total &&
          tally == o.tally &&
          buckets == o.buckets &&
          recent_failures == o.recent_failures &&
          next_scheduled == o.next_scheduled
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [total, tally, buckets, recent_failures, next_scheduled].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
