=begin
#smplkit Jobs API

#Scheduled HTTP job execution API for smplkit.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::Jobs
  # Current-period usage against the account's plan allotments.
  class Usage < ApiModelBase
    # The usage period this report covers, as `YYYY-MM` (UTC).
    attr_accessor :period

    # Runs metered so far this period.
    attr_accessor :runs_used

    # Runs included in the plan this period (`-1` means unlimited).
    attr_accessor :runs_included

    # Number of currently-enabled jobs.
    attr_accessor :active_jobs

    # Maximum enabled jobs the plan allows (`-1` means unlimited).
    attr_accessor :active_jobs_limit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'period' => :'period',
        :'runs_used' => :'runs_used',
        :'runs_included' => :'runs_included',
        :'active_jobs' => :'active_jobs',
        :'active_jobs_limit' => :'active_jobs_limit'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'period' => :'String',
        :'runs_used' => :'Integer',
        :'runs_included' => :'Integer',
        :'active_jobs' => :'Integer',
        :'active_jobs_limit' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SmplkitGeneratedClient::Jobs::Usage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SmplkitGeneratedClient::Jobs::Usage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'period')
        self.period = attributes[:'period']
      else
        self.period = nil
      end

      if attributes.key?(:'runs_used')
        self.runs_used = attributes[:'runs_used']
      else
        self.runs_used = nil
      end

      if attributes.key?(:'runs_included')
        self.runs_included = attributes[:'runs_included']
      else
        self.runs_included = nil
      end

      if attributes.key?(:'active_jobs')
        self.active_jobs = attributes[:'active_jobs']
      else
        self.active_jobs = nil
      end

      if attributes.key?(:'active_jobs_limit')
        self.active_jobs_limit = attributes[:'active_jobs_limit']
      else
        self.active_jobs_limit = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @period.nil?
        invalid_properties.push('invalid value for "period", period cannot be nil.')
      end

      if @runs_used.nil?
        invalid_properties.push('invalid value for "runs_used", runs_used cannot be nil.')
      end

      if @runs_included.nil?
        invalid_properties.push('invalid value for "runs_included", runs_included cannot be nil.')
      end

      if @active_jobs.nil?
        invalid_properties.push('invalid value for "active_jobs", active_jobs cannot be nil.')
      end

      if @active_jobs_limit.nil?
        invalid_properties.push('invalid value for "active_jobs_limit", active_jobs_limit cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @period.nil?
      return false if @runs_used.nil?
      return false if @runs_included.nil?
      return false if @active_jobs.nil?
      return false if @active_jobs_limit.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] period Value to be assigned
    def period=(period)
      if period.nil?
        fail ArgumentError, 'period cannot be nil'
      end

      @period = period
    end

    # Custom attribute writer method with validation
    # @param [Object] runs_used Value to be assigned
    def runs_used=(runs_used)
      if runs_used.nil?
        fail ArgumentError, 'runs_used cannot be nil'
      end

      @runs_used = runs_used
    end

    # Custom attribute writer method with validation
    # @param [Object] runs_included Value to be assigned
    def runs_included=(runs_included)
      if runs_included.nil?
        fail ArgumentError, 'runs_included cannot be nil'
      end

      @runs_included = runs_included
    end

    # Custom attribute writer method with validation
    # @param [Object] active_jobs Value to be assigned
    def active_jobs=(active_jobs)
      if active_jobs.nil?
        fail ArgumentError, 'active_jobs cannot be nil'
      end

      @active_jobs = active_jobs
    end

    # Custom attribute writer method with validation
    # @param [Object] active_jobs_limit Value to be assigned
    def active_jobs_limit=(active_jobs_limit)
      if active_jobs_limit.nil?
        fail ArgumentError, 'active_jobs_limit cannot be nil'
      end

      @active_jobs_limit = active_jobs_limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          period == o.period &&
          runs_used == o.runs_used &&
          runs_included == o.runs_included &&
          active_jobs == o.active_jobs &&
          active_jobs_limit == o.active_jobs_limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [period, runs_used, runs_included, active_jobs, active_jobs_limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
