# frozen_string_literal: true

module Smplkit
  # Rails integration for the smplkit gem.
  #
  # The Railtie is loaded only when +Rails::Railtie+ is defined, so non-Rails
  # customers pay zero load cost.
  #
  # Customers configure smplkit through +config.smplkit.*+ in
  # +config/initializers/smplkit.rb+, generated by
  # +rails generate smplkit:install+.
  class Railtie < ::Rails::Railtie
    config.smplkit = ActiveSupport::OrderedOptions.new

    initializer "smplkit.configure" do |app|
      Smplkit.configure_for_rails(app.config.smplkit)
    end

    generators do
      require_relative "generators/install_generator"
    end
  end

  module_function

  # Construct the global +Smplkit.client+ from a Rails-friendly options
  # struct. Falls back to +SMPLKIT_*+ env vars + +~/.smplkit+ resolution
  # for any field the customer left blank.
  def configure_for_rails(options)
    client = Client.new(
      api_key: options.api_key,
      environment: options.environment || (defined?(::Rails) ? ::Rails.env : nil),
      service: options.service,
      profile: options.profile,
      base_domain: options.base_domain,
      scheme: options.scheme,
      debug: options.debug,
      telemetry: options.telemetry
    )
    @client = client
    @context_provider = options.context_provider
    client
  end

  class << self
    attr_accessor :client, :context_provider
  end
end
