=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Audit::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Audit::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Audit::EventsApi)
    end
  end

  # unit tests for get_event
  # Get Event
  # Retrieve a single audit event by id.
  # @param event_id 
  # @param [Hash] opts the optional parameters
  # @return [EventResponse]
  describe 'get_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_events
  # List Events
  # List audit events for this account.  Default sort is &#x60;-occurred_at&#x60; (newest occurrence first). Sort by &#x60;occurred_at&#x60; or &#x60;created_at&#x60;, ascending or descending — keep the same &#x60;sort&#x60; value across paginated requests so the cursor stays consistent. Filters are exact-match except &#x60;filter[occurred_at]&#x60;, which uses interval notation (e.g. &#x60;[2026-01-01T00:00:00Z,2026-01-31T00:00:00Z)&#x60;), and &#x60;filter[search]&#x60;, which is a case-insensitive substring match against &#x60;resource_id&#x60; or &#x60;description&#x60;.  Two filter-combination rules:  - &#x60;filter[resource_id]&#x60; must be accompanied by &#x60;filter[resource_type]&#x60;   (the index is keyed on the pair). - &#x60;filter[search]&#x60; must be accompanied by either &#x60;filter[occurred_at]&#x60;   or &#x60;filter[resource_type]&#x60; + &#x60;filter[resource_id]&#x60; (substring   matching has no index, so an unbounded substring scan is rejected).  No other filter combinations are required — calling the endpoint with no query parameters returns the latest events for the account, paginated.  &#x60;page[size]&#x60; defaults to 1000 and must not exceed 1000.  Pass &#x60;format&#x3D;CSV&#x60; or &#x60;format&#x3D;JSONL&#x60; to stream a download of the full filtered result set instead of a paginated JSON:API response. The download honors every supplied filter and ignores &#x60;page[size]&#x60; and &#x60;page[after]&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_occurred_at 
  # @option opts [String] :filter_actor_type 
  # @option opts [String] :filter_actor_id 
  # @option opts [String] :filter_event_type 
  # @option opts [String] :filter_resource_type 
  # @option opts [String] :filter_resource_id 
  # @option opts [String] :filter_search Case-insensitive substring match against &#x60;resource_id&#x60; or &#x60;description&#x60;. Use &#x60;filter[resource_id]&#x60; for an exact match on &#x60;resource_id&#x60;.
  # @option opts [Boolean] :filter_do_not_forward When set, restrict to events whose &#x60;do_not_forward&#x60; flag matches the given boolean. Forwarder previews typically pass &#x60;false&#x60; to match live-pipeline semantics (events flagged &#x60;do_not_forward&#x3D;true&#x60; are skipped by the forwarder pipeline).
  # @option opts [Integer] :page_size 
  # @option opts [String] :page_after 
  # @option opts [String] :format When set, stream a download of the full filtered result set in the chosen format instead of returning a paginated JSON:API response. &#x60;page[size]&#x60; and &#x60;page[after]&#x60; are ignored in this mode; every event matching the supplied filters is emitted. &#x60;CSV&#x60; writes one row per event with the event payload (&#x60;data&#x60;) serialized as a single JSON-encoded cell. &#x60;JSONL&#x60; writes one JSON object per line with the event payload nested as a JSON object. Omit this parameter to receive the paginated JSON:API response.
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-occurred_at&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;occurred_at&#x60;, &#x60;-occurred_at&#x60;.
  # @return [EventListResponse]
  describe 'list_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for record_event
  # Record Event
  # Record an audit event for this account.  Returns &#x60;201 Created&#x60; on first write, &#x60;200 OK&#x60; if the request was a duplicate (matched by &#x60;Idempotency-Key&#x60; or a key derived from the event&#39;s content).  &#x60;resource_type&#x60; values beginning with &#x60;smpl.&#x60; are reserved for events that smplkit emits about its own resources and cannot be used here.
  # @param event_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [EventResponse]
  describe 'record_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_events
  # Search Events
  # Search audit events with column filters and an optional JSON Logic expression.  Without a JSON Logic &#x60;filter&#x60;: behaves like &#x60;GET /api/v1/events&#x60; with the same column filters.  With a JSON Logic &#x60;filter&#x60;: the search is silently capped to the last 30 days by &#x60;occurred_at&#x60; (intersected with any explicit &#x60;filter[occurred_at]&#x60; the caller supplied), the column filters narrow the candidate set in SQL, and the JSON Logic expression runs in memory against each candidate row using the same &#x60;json-logic-qubit&#x60; evaluator the forwarder pipeline uses. Up to 50,000 rows are scanned per request; the response&#39;s &#x60;meta.scan&#x60; block reports the scan stats so a selective filter doesn&#39;t look like \&quot;0 matches\&quot; when the truth is \&quot;ceiling reached.\&quot;
  # @param event_search_request 
  # @param [Hash] opts the optional parameters
  # @return [EventSearchResponse]
  describe 'search_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
