=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Audit::FunctionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FunctionsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Audit::FunctionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FunctionsApi' do
    it 'should create an instance of FunctionsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Audit::FunctionsApi)
    end
  end

  # unit tests for execute_wipe
  # Execute Wipe
  # Delete every audit-database row scoped to the authenticated account.  Returns the per-table row counts that were deleted along with the completion timestamp. The action is atomic within the audit database — either every account-scoped row is gone, or none is. The body is required to be &#x60;&#x60;{}&#x60;&#x60;; no parameters are accepted.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [WipeResponse]
  describe 'execute_wipe test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
