=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::Audit
  # The catalog entry's attributes — one branded forwarder type or the synthetic Custom HTTP entry.
  class ForwarderTypeAttributes < ApiModelBase
    # Human-readable label shown in the type-picker.
    attr_accessor :name

    # Absolute URL to the icon asset, served by audit at `/api/v1/forwarder_types/{id}/icon`.
    attr_accessor :icon

    # Transport family — today only `HTTP`. New base types will add their own configuration shape and runtime handler.
    attr_accessor :base_type

    # Link to the vendor's own documentation for this destination.
    attr_accessor :docs_url

    # True for the synthetic `http` Custom HTTP entry, which has no vendor template — the customer supplies URL, headers, and transform from scratch. False for branded types.
    attr_accessor :is_custom

    # Delivery template. Shape depends on `base_type`.
    attr_accessor :configuration

    # UI metadata keyed by placeholder name. Each `{name}` token appearing in `configuration` (URL, header value) has a matching entry here describing how to prompt for it.
    attr_accessor :placeholders

    # Default transform shipped with the type, or `null` if none.
    attr_accessor :transform

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'icon' => :'icon',
        :'base_type' => :'base_type',
        :'docs_url' => :'docs_url',
        :'is_custom' => :'is_custom',
        :'configuration' => :'configuration',
        :'placeholders' => :'placeholders',
        :'transform' => :'transform'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'icon' => :'String',
        :'base_type' => :'String',
        :'docs_url' => :'String',
        :'is_custom' => :'Boolean',
        :'configuration' => :'ForwarderTypeHttpConfiguration',
        :'placeholders' => :'Hash<String, ForwarderTypePlaceholder>',
        :'transform' => :'ForwarderTypeTransform'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'docs_url',
        :'transform'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SmplkitGeneratedClient::Audit::ForwarderTypeAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SmplkitGeneratedClient::Audit::ForwarderTypeAttributes`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'icon')
        self.icon = attributes[:'icon']
      else
        self.icon = nil
      end

      if attributes.key?(:'base_type')
        self.base_type = attributes[:'base_type']
      else
        self.base_type = nil
      end

      if attributes.key?(:'docs_url')
        self.docs_url = attributes[:'docs_url']
      end

      if attributes.key?(:'is_custom')
        self.is_custom = attributes[:'is_custom']
      else
        self.is_custom = nil
      end

      if attributes.key?(:'configuration')
        self.configuration = attributes[:'configuration']
      else
        self.configuration = nil
      end

      if attributes.key?(:'placeholders')
        if (value = attributes[:'placeholders']).is_a?(Hash)
          self.placeholders = value
        end
      else
        self.placeholders = nil
      end

      if attributes.key?(:'transform')
        self.transform = attributes[:'transform']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @icon.nil?
        invalid_properties.push('invalid value for "icon", icon cannot be nil.')
      end

      if @base_type.nil?
        invalid_properties.push('invalid value for "base_type", base_type cannot be nil.')
      end

      if @is_custom.nil?
        invalid_properties.push('invalid value for "is_custom", is_custom cannot be nil.')
      end

      if @configuration.nil?
        invalid_properties.push('invalid value for "configuration", configuration cannot be nil.')
      end

      if @placeholders.nil?
        invalid_properties.push('invalid value for "placeholders", placeholders cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @icon.nil?
      return false if @base_type.nil?
      return false if @is_custom.nil?
      return false if @configuration.nil?
      return false if @placeholders.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] icon Value to be assigned
    def icon=(icon)
      if icon.nil?
        fail ArgumentError, 'icon cannot be nil'
      end

      @icon = icon
    end

    # Custom attribute writer method with validation
    # @param [Object] base_type Value to be assigned
    def base_type=(base_type)
      if base_type.nil?
        fail ArgumentError, 'base_type cannot be nil'
      end

      @base_type = base_type
    end

    # Custom attribute writer method with validation
    # @param [Object] is_custom Value to be assigned
    def is_custom=(is_custom)
      if is_custom.nil?
        fail ArgumentError, 'is_custom cannot be nil'
      end

      @is_custom = is_custom
    end

    # Custom attribute writer method with validation
    # @param [Object] configuration Value to be assigned
    def configuration=(configuration)
      if configuration.nil?
        fail ArgumentError, 'configuration cannot be nil'
      end

      @configuration = configuration
    end

    # Custom attribute writer method with validation
    # @param [Object] placeholders Value to be assigned
    def placeholders=(placeholders)
      if placeholders.nil?
        fail ArgumentError, 'placeholders cannot be nil'
      end

      @placeholders = placeholders
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          icon == o.icon &&
          base_type == o.base_type &&
          docs_url == o.docs_url &&
          is_custom == o.is_custom &&
          configuration == o.configuration &&
          placeholders == o.placeholders &&
          transform == o.transform
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, icon, base_type, docs_url, is_custom, configuration, placeholders, transform].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
