=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::Audit
  class ForwarderType
    HTTP = "http".freeze
    DATADOG = "datadog".freeze
    SPLUNK_HEC = "splunk_hec".freeze
    SUMO_LOGIC = "sumo_logic".freeze
    NEW_RELIC = "new_relic".freeze
    HONEYCOMB = "honeycomb".freeze
    ELASTIC = "elastic".freeze

    def self.all_vars
      @all_vars ||= [HTTP, DATADOG, SPLUNK_HEC, SUMO_LOGIC, NEW_RELIC, HONEYCOMB, ELASTIC].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ForwarderType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ForwarderType"
    end
  end
end
