=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module SmplkitGeneratedClient::Audit
  # Result of a test-forwarder execution.
  class TestForwarderResponse < ApiModelBase
    # True if the destination responded with a status matching `success_status`.
    attr_accessor :succeeded

    # HTTP status code returned by the destination.
    attr_accessor :response_status

    # Headers returned by the destination.
    attr_accessor :response_headers

    # Response body returned by the destination.
    attr_accessor :response_body

    # Elapsed time of the request in milliseconds.
    attr_accessor :latency_ms

    # Error message if the request did not complete.
    attr_accessor :error

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'succeeded' => :'succeeded',
        :'response_status' => :'response_status',
        :'response_headers' => :'response_headers',
        :'response_body' => :'response_body',
        :'latency_ms' => :'latency_ms',
        :'error' => :'error'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'succeeded' => :'Boolean',
        :'response_status' => :'Integer',
        :'response_headers' => :'Hash<String, String>',
        :'response_body' => :'String',
        :'latency_ms' => :'Integer',
        :'error' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'response_status',
        :'response_body',
        :'latency_ms',
        :'error'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SmplkitGeneratedClient::Audit::TestForwarderResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SmplkitGeneratedClient::Audit::TestForwarderResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'succeeded')
        self.succeeded = attributes[:'succeeded']
      else
        self.succeeded = nil
      end

      if attributes.key?(:'response_status')
        self.response_status = attributes[:'response_status']
      else
        self.response_status = nil
      end

      if attributes.key?(:'response_headers')
        if (value = attributes[:'response_headers']).is_a?(Hash)
          self.response_headers = value
        end
      end

      if attributes.key?(:'response_body')
        self.response_body = attributes[:'response_body']
      end

      if attributes.key?(:'latency_ms')
        self.latency_ms = attributes[:'latency_ms']
      else
        self.latency_ms = nil
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @succeeded.nil?
        invalid_properties.push('invalid value for "succeeded", succeeded cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @succeeded.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] succeeded Value to be assigned
    def succeeded=(succeeded)
      if succeeded.nil?
        fail ArgumentError, 'succeeded cannot be nil'
      end

      @succeeded = succeeded
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          succeeded == o.succeeded &&
          response_status == o.response_status &&
          response_headers == o.response_headers &&
          response_body == o.response_body &&
          latency_ms == o.latency_ms &&
          error == o.error
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [succeeded, response_status, response_headers, response_body, latency_ms, error].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
