# -*- encoding: utf-8 -*-

=begin
#smplkit Audit API

#Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "smplkit_audit_client/version"

Gem::Specification.new do |s|
  s.name        = "smplkit_audit_client"
  s.version     = SmplkitGeneratedClient::Audit::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://github.com/smplkit/ruby-sdk"
  s.summary     = "smplkit Audit API Ruby Gem"
  s.description = "Append-only change-history substrate for smpl.* resources and customer-application events. ADR-047."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
