=begin
#smplkit Jobs API

#Scheduled HTTP job execution API for smplkit.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'smplkit_jobs_client/api_client'
require 'smplkit_jobs_client/api_error'
require 'smplkit_jobs_client/api_model_base'
require 'smplkit_jobs_client/version'
require 'smplkit_jobs_client/configuration'

# Models
require 'smplkit_jobs_client/models/error'
require 'smplkit_jobs_client/models/error_response'
require 'smplkit_jobs_client/models/http_header'
require 'smplkit_jobs_client/models/job'
require 'smplkit_jobs_client/models/job_create_request'
require 'smplkit_jobs_client/models/job_create_resource'
require 'smplkit_jobs_client/models/job_environment'
require 'smplkit_jobs_client/models/job_http_configuration'
require 'smplkit_jobs_client/models/job_list_response'
require 'smplkit_jobs_client/models/job_request'
require 'smplkit_jobs_client/models/job_resource'
require 'smplkit_jobs_client/models/job_response'
require 'smplkit_jobs_client/models/list_meta'
require 'smplkit_jobs_client/models/pagination_meta'
require 'smplkit_jobs_client/models/retry_on'
require 'smplkit_jobs_client/models/retry_policy'
require 'smplkit_jobs_client/models/retry_policy_create_request'
require 'smplkit_jobs_client/models/retry_policy_create_resource'
require 'smplkit_jobs_client/models/retry_policy_list_response'
require 'smplkit_jobs_client/models/retry_policy_request'
require 'smplkit_jobs_client/models/retry_policy_resource'
require 'smplkit_jobs_client/models/retry_policy_response'
require 'smplkit_jobs_client/models/run'
require 'smplkit_jobs_client/models/run_list_links'
require 'smplkit_jobs_client/models/run_list_meta'
require 'smplkit_jobs_client/models/run_list_response'
require 'smplkit_jobs_client/models/run_resource'
require 'smplkit_jobs_client/models/run_response'
require 'smplkit_jobs_client/models/run_retry'
require 'smplkit_jobs_client/models/usage'
require 'smplkit_jobs_client/models/usage_resource'
require 'smplkit_jobs_client/models/usage_response'

# APIs
require 'smplkit_jobs_client/api/jobs_api'
require 'smplkit_jobs_client/api/retry_policies_api'
require 'smplkit_jobs_client/api/runs_api'
require 'smplkit_jobs_client/api/usage_api'

module SmplkitGeneratedClient::Jobs
  class << self
    # Customize default settings for the SDK using block.
    #   SmplkitGeneratedClient::Jobs.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
