=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::BillingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::BillingApi)
    end
  end

  # unit tests for create_payment_method
  # Add Payment Method
  # Register a Stripe payment method (&#x60;pm_...&#x60;) on the account. The client first creates the Stripe payment method using a SetupIntent and Stripe Elements, then submits its identifier here to persist it.
  # @param add_payment_method_body 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'create_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_payment_method
  # Delete Payment Method
  # Delete a payment method. Returns 409 if this is the only payment method on file and the account has an active paid subscription. If the deleted payment method was the default, the oldest remaining payment method is promoted to default.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for execute_setup_intent
  # Execute Setup Intent
  # Create a Stripe SetupIntent for adding a payment method without an immediate charge. Returns the &#x60;client_secret&#x60; to pass to Stripe Elements in the browser.
  # @param [Hash] opts the optional parameters
  # @return [SetupIntentResponse]
  describe 'execute_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_invoice
  # Get Invoice
  # Return a single invoice by id. Supports content negotiation via the &#x60;Accept&#x60; header:  - &#x60;application/pdf&#x60; — streams the invoice PDF. - &#x60;application/vnd.api+json&#x60;, &#x60;application/json&#x60;, or absent — returns   the JSON:API invoice resource. - Any other value — &#x60;406 Not Acceptable&#x60;.
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceSingleResponse]
  describe 'get_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payment_method
  # Get Payment Method
  # Return a payment method by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'get_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_invoices
  # List Invoices
  # Return invoice history for the account from Stripe.  Default sort is &#x60;-created_at&#x60; (newest first). The endpoint fetches the most recent 100 invoices from Stripe (its per-request cap) and pages over the result in memory; clients should not depend on more than 100 invoices being visible at once.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-created_at&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;status&#x60;, &#x60;-status&#x60;, &#x60;total&#x60;, &#x60;-total&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [InvoiceListResponse]
  describe 'list_invoices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_payment_methods
  # List Payment Methods
  # List all payment methods for the account. Default is returned first, then newest first.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-created_at&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;exp_year&#x60;, &#x60;-exp_year&#x60;, &#x60;is_default&#x60;, &#x60;-is_default&#x60;, &#x60;updated_at&#x60;, &#x60;-updated_at&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [PaymentMethodListResponse]
  describe 'list_payment_methods test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_default_payment_method
  # Set Default Payment Method
  # Mark this payment method as the account&#39;s default. Idempotent: returns 200 with no changes when the payment method is already the default.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'set_default_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_payment_method
  # Update Payment Method
  # Update the mutable fields of a payment method (&#x60;billing_details&#x60;, &#x60;exp_month&#x60;, &#x60;exp_year&#x60;). The &#x60;default&#x60; flag is not mutable via PUT — use the &#x60;set_default&#x60; action instead.
  # @param id 
  # @param payment_method_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'update_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
