=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::DiscountTiersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DiscountTiersApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::DiscountTiersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DiscountTiersApi' do
    it 'should create an instance of DiscountTiersApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::DiscountTiersApi)
    end
  end

  # unit tests for list_discount_tiers
  # List Discount Tiers
  # Return the multi-product volume discount schedule.  Each tier is identified by the minimum number of paid products at which the discount applies. The first tier (1 product) carries no discount; subsequent tiers grant a progressively larger percent off every paid subscription item. Default sort is &#x60;products_count&#x60; ascending, which is the natural ladder customers traverse as they add products.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;products_count&#x60;. Allowed values: &#x60;percent_off&#x60;, &#x60;-percent_off&#x60;, &#x60;products_count&#x60;, &#x60;-products_count&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [DiscountTierListResponse]
  describe 'list_discount_tiers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
