=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::EmailRegistrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmailRegistrationsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::EmailRegistrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailRegistrationsApi' do
    it 'should create an instance of EmailRegistrationsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::EmailRegistrationsApi)
    end
  end

  # unit tests for create_email_registration
  # Register for Launch List
  # Submit an email address to the smplkit launch list. Sends a notification to support@smplkit.com. No authentication required. Nothing is persisted.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_email_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
