=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::EnvironmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EnvironmentsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::EnvironmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnvironmentsApi' do
    it 'should create an instance of EnvironmentsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::EnvironmentsApi)
    end
  end

  # unit tests for create_environment
  # Create Environment
  # Create a new environment. The caller provides the id (key) in the request body.
  # @param environment_request 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'create_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_environment
  # Delete Environment
  # Delete an environment by id. When &#x60;cascade&#x3D;true&#x60; is set, also remove every per-environment reference held by flags, configs, and loggers in the corresponding services before deleting the environment row. The default &#x60;cascade&#x3D;false&#x60; deletes only the environment row, leaving downstream references in place.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :cascade When &#x60;true&#x60;, remove every flag rule, env-level flag default, config override, and logger override scoped to this environment before deleting the environment row.
  # @return [nil]
  describe 'delete_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_environment
  # Get Environment
  # Return an environment by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'get_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_environment_usage
  # Report Environment Usage
  # Report how many flag rules, env-level flag defaults, config overrides, and logger overrides reference this environment. Used by the console&#39;s delete dialog so the user can see what would survive a non-cascading delete.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentUsageResponse]
  describe 'get_environment_usage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_environments
  # List Environments
  # List all environments for the authenticated account.
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentListResponse]
  describe 'list_environments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_environment
  # Update Environment
  # Update an environment by id.
  # @param id 
  # @param environment_request 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'update_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
