=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::EnvironmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EnvironmentsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::EnvironmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnvironmentsApi' do
    it 'should create an instance of EnvironmentsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::EnvironmentsApi)
    end
  end

  # unit tests for create_environment
  # Create Environment
  # Create a new environment. The caller provides the id (key) in the request body.
  # @param environment_request 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'create_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_environment
  # Delete Environment
  # Delete an environment by id. When &#x60;cascade&#x3D;true&#x60; is set, also remove every per-environment reference held by flags, configs, and loggers in the corresponding services before deleting the environment row. The default &#x60;cascade&#x3D;false&#x60; deletes only the environment row, leaving downstream references in place.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :cascade When &#x60;true&#x60;, remove every flag rule, env-level flag default, config override, and logger override scoped to this environment before deleting the environment row.
  # @return [nil]
  describe 'delete_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_environment
  # Get Environment
  # Return an environment by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'get_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_environment_usage
  # Report Environment Usage
  # Report how many flag rules, env-level flag defaults, config overrides, and logger overrides reference this environment. Used by the console&#39;s delete dialog so the user can see what would survive a non-cascading delete.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentUsageResponse]
  describe 'get_environment_usage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_environments
  # List Environments
  # List all environments for the authenticated account. &#x60;filter[search]&#x60; does a case-insensitive substring match against the environment &#x60;key&#x60; and &#x60;name&#x60;. &#x60;filter[classification]&#x60; narrows the result to one classification (&#x60;STANDARD&#x60; or &#x60;AD_HOC&#x60;).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_search Case-insensitive substring match against the environment &#x60;key&#x60; and &#x60;name&#x60;. An environment is returned if either field contains the search term.
  # @option opts [String] :filter_classification Narrow the result to environments with the given classification. One of &#x60;STANDARD&#x60; or &#x60;AD_HOC&#x60;.
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;name&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;key&#x60;, &#x60;-key&#x60;, &#x60;name&#x60;, &#x60;-name&#x60;, &#x60;updated_at&#x60;, &#x60;-updated_at&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [EnvironmentListResponse]
  describe 'list_environments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_environment
  # Update Environment
  # Update an environment by id.
  # @param id 
  # @param environment_request 
  # @param [Hash] opts the optional parameters
  # @return [EnvironmentResponse]
  describe 'update_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
