=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::GroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instance of GroupsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::GroupsApi)
    end
  end

  # unit tests for create_group
  # Create Group
  # Create an Environment Access Group. The caller provides the group id (a snake-case key, unique within the account) in the request body. The id is immutable thereafter. Returns &#x60;409&#x60; if a group with that id already exists, or &#x60;422&#x60; if &#x60;managed_environments&#x60; is not exactly &#x60;[&#39;*&#39;]&#x60; or a subset of the account&#39;s standard environment keys.
  # @param group_create_request 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponse]
  describe 'create_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_group
  # Delete Group
  # Delete a group by id. Returns &#x60;409&#x60; for the reserved &#x60;default&#x60; group, which every account requires. Deleting a group also cascades to its memberships.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_group
  # Get Group
  # Return a group by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponse]
  describe 'get_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_groups
  # List Groups
  # List Environment Access Groups for the authenticated account. &#x60;filter[search]&#x60; does a case-insensitive substring match against the group &#x60;key&#x60; and &#x60;name&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_search Case-insensitive substring match against the group &#x60;key&#x60; and &#x60;name&#x60;. A group is returned if either field contains the search term.
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;name&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;key&#x60;, &#x60;-key&#x60;, &#x60;name&#x60;, &#x60;-name&#x60;, &#x60;updated_at&#x60;, &#x60;-updated_at&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [GroupListResponse]
  describe 'list_groups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_group
  # Update Group
  # Update a group&#39;s name, description, and managed environments. Whole-resource semantics — submit every writable attribute. For the reserved &#x60;default&#x60; group, &#x60;managed_environments&#x60; may be changed (this is the lever that narrows the account-wide baseline), but renaming or other identity changes are rejected with &#x60;409&#x60;. Invalid &#x60;managed_environments&#x60; is &#x60;422&#x60;.
  # @param id 
  # @param group_request 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponse]
  describe 'update_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
