=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::InvitationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvitationsApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::InvitationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvitationsApi' do
    it 'should create an instance of InvitationsApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::InvitationsApi)
    end
  end

  # unit tests for accept_invitation
  # Accept Invitation
  # Accept an invitation using a token from the invitation email.
  # @param invitation_accept_request 
  # @param [Hash] opts the optional parameters
  # @return [InvitationResponse]
  describe 'accept_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_invitations
  # Bulk Create Invitations
  # Send one or more invitations to join the account.
  # @param invitation_bulk_create_request 
  # @param [Hash] opts the optional parameters
  # @return [InvitationListResponse]
  describe 'create_invitations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_invitations
  # List Invitations
  # List invitations. Authenticated admins list invitations for their own account and may narrow by status. Unauthenticated callers must pass &#x60;&#x60;filter[token]&#x60;&#x60; to look up a specific invitation by its token — used to render the invitation preview before sign-in. The token-filter path always returns an array of 0 or 1 elements.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_status 
  # @option opts [String] :filter_token 
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;-created_at&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;email&#x60;, &#x60;-email&#x60;, &#x60;status&#x60;, &#x60;-status&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [InvitationListResponse]
  describe 'list_invitations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resend_invitation
  # Resend Invitation
  # Resend a pending invitation email by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InvitationResponse]
  describe 'resend_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_invitation
  # Revoke Invitation
  # Revoke a pending invitation by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InvitationResponse]
  describe 'revoke_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
