=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::ServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServicesApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::ServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicesApi' do
    it 'should create an instance of ServicesApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::ServicesApi)
    end
  end

  # unit tests for create_service
  # Create Service
  # Create a new service. The caller provides the id (key) in the request body.
  # @param service_request 
  # @param [Hash] opts the optional parameters
  # @return [ServiceResponse]
  describe 'create_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_service
  # Delete Service
  # Delete a service by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service
  # Get Service
  # Return a service by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ServiceResponse]
  describe 'get_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_services
  # List Services
  # List all services for the authenticated account.
  # @param [Hash] opts the optional parameters
  # @return [ServiceListResponse]
  describe 'list_services test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_service
  # Update Service
  # Update a service by id.
  # @param id 
  # @param service_request 
  # @param [Hash] opts the optional parameters
  # @return [ServiceResponse]
  describe 'update_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
