=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::SSOApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SSOApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::SSOApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SSOApi' do
    it 'should create an instance of SSOApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::SSOApi)
    end
  end

  # unit tests for claim_sso_domain
  # Claim SSO Domain
  # Claim a domain for SSO routing. Idempotent — re-claiming a domain already held by the account is a no-op success. The response includes the DNS TXT token to publish.
  # @param domain 
  # @param sso_domain_request 
  # @param [Hash] opts the optional parameters
  # @return [SSODomainResponse]
  describe 'claim_sso_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sso_connection
  # Delete SSO Connection
  # Soft-delete the account&#39;s SSO connection. Domains are preserved.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_sso_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sso_connection
  # Get SSO Connection
  # Return the SSO connection for the current account, including computed Service Provider metadata. Returns &#x60;404&#x60; when no connection has been configured.
  # @param [Hash] opts the optional parameters
  # @return [SSOConnectionResponse]
  describe 'get_sso_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sso_domains
  # List SSO Domains
  # List the domains claimed by the current account, including each row&#39;s verification status.
  # @param [Hash] opts the optional parameters
  # @return [SSODomainListResponse]
  describe 'list_sso_domains test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_sso_connection
  # Create or Replace SSO Connection
  # Create-or-replace the account&#39;s SSO connection. The OIDC &#x60;client_secret&#x60; is write-only; supply it on first creation, omit on subsequent updates to retain the stored value.
  # @param sso_connection_request 
  # @param [Hash] opts the optional parameters
  # @return [SSOConnectionResponse]
  describe 'put_sso_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for release_sso_domain
  # Release SSO Domain
  # Release a previously-claimed SSO domain.
  # @param domain 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'release_sso_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for verify_sso_domain
  # Verify SSO Domain
  # Run the DNS TXT check for a claimed domain. Returns the updated resource on success. Returns &#x60;409&#x60; if a different account has already verified this domain. Returns &#x60;422&#x60; when the DNS TXT record has not yet been published or does not match the expected token.
  # @param domain 
  # @param [Hash] opts the optional parameters
  # @return [SSODomainResponse]
  describe 'verify_sso_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
