=begin
#smplkit API

#API for the smplkit platform.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::App::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::App::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::App::UsersApi)
    end
  end

  # unit tests for get_current_user
  # Get Current User
  # Return the currently authenticated user. &#x60;&#x60;role&#x60;&#x60; and &#x60;&#x60;account&#x60;&#x60; are populated when the user has a membership; both are null when the caller is authenticated but has no account yet — e.g. a returning user who has just accepted an invitation email.
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'get_current_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user
  # Get User
  # Return a user by id.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'get_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_settings
  # Get User Settings
  # Return the current user&#39;s settings as plain JSON.
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_user_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users
  # List Users
  # List users in the authenticated account.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_account 
  # @option opts [String] :filter_email 
  # @option opts [String] :filter_search Case-insensitive substring match against display_name and email. If the value is a valid UUID, also matches user id exactly.
  # @option opts [String] :sort Field to sort by. Prefix with &#x60;-&#x60; for descending order. Default: &#x60;email&#x60;. Allowed values: &#x60;created_at&#x60;, &#x60;-created_at&#x60;, &#x60;display_name&#x60;, &#x60;-display_name&#x60;, &#x60;email&#x60;, &#x60;-email&#x60;.
  # @option opts [Integer] :page_number 1-based page number to return. Optional; defaults to &#x60;1&#x60; when omitted. Must be &#x60;&gt;&#x3D; 1&#x60; — requests with a smaller value are rejected with a 400 error.
  # @option opts [Integer] :page_size Number of items per page. Optional; defaults to &#x60;1000&#x60; when omitted. Must be between &#x60;1&#x60; and &#x60;1000&#x60; inclusive — requests outside that range are rejected with a 400 error.
  # @option opts [Boolean] :meta_total When &#x60;true&#x60;, the response&#39;s &#x60;meta.pagination&#x60; block includes &#x60;total&#x60; (the total number of matching items across all pages) and &#x60;total_pages&#x60;. Computing these requires an extra &#x60;COUNT&#x60; query, so omit (or pass &#x60;false&#x60;) when the totals are not needed. Defaults to &#x60;false&#x60;.
  # @return [UserListResponse]
  describe 'list_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_user_settings
  # Update User Settings
  # Replace the current user&#39;s settings with the provided JSON object.
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'put_user_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_user_settings_key
  # Update User Setting by Key
  # Set a single key in the current user&#39;s settings. The key is stored as a flat literal key (dot-notation is NOT expanded to nested paths). Returns the full updated settings object.
  # @param key 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'put_user_settings_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_user
  # Remove User
  # Remove a user from the account.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_current_user
  # Update Current User
  # Update the currently authenticated user&#39;s profile.
  # @param user_request 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'update_current_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_role
  # Update User Role
  # Update a user&#39;s role in the account.
  # @param id 
  # @param user_request 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'update_user_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
