# frozen_string_literal: true

# Generates Gemfile.floor: every customer-facing runtime dependency pinned to
# the lowest version a consumer could actually install together — i.e. the
# lowest MUTUALLY-COMPATIBLE set satisfying the gemspec constraints. This lets
# CI prove the declared floors are real and not aspirational.
#
# Bundler has no native lowest-version resolver, and the gems are version-
# coupled (e.g. async-http's own floor requires a newer async than async's
# gemspec floor), so a naive per-gem floor pin is un-installable. We resolve
# the lowest co-installable set ourselves: start each direct runtime dep at its
# own lowest published version, then iterate to a fixpoint, raising any sibling
# floor that a chosen version transitively requires above its current pin.
#
# Dev/test tooling is copied verbatim from the main Gemfile and kept current.
# Everything is derived from the gemspec / Gemfile — nothing to hand-maintain.

require "rubygems"
require "rubygems/spec_fetcher"

FETCHER = Gem::SpecFetcher.fetcher

# Lowest published, non-prerelease version satisfying +req+, or nil.
def lowest_satisfying(name, req)
  dep = Gem::Dependency.new(name, req)
  tuples = FETCHER.spec_for_dependency(dep).first
  tuples.map { |t, _| t.version }
        .reject(&:prerelease?)
        .select { |v| req.satisfied_by?(v) }
        .min
end

# Runtime dependencies of a specific published version of +name+.
def runtime_deps_of(name, version)
  dep = Gem::Dependency.new(name, "= #{version}")
  pair = FETCHER.spec_for_dependency(dep).first.find { |t, _| t.version == version }
  return [] unless pair
  name_tuple, source = pair
  source.fetch_spec(name_tuple).runtime_dependencies
end

spec = Gem::Specification.load(Dir["*.gemspec"].first)
runtime = spec.dependencies.select { |d| d.type == :runtime }
gemspec_req = runtime.to_h { |d| [d.name, d.requirement] }
direct = gemspec_req.keys

# Seed each direct dep at its own gemspec floor, then raise to a fixpoint so the
# set is mutually co-installable.
floor = direct.to_h { |n| [n, lowest_satisfying(n, gemspec_req[n])] }
loop do
  changed = false
  direct.each do |n|
    runtime_deps_of(n, floor[n]).each do |dep|
      next unless direct.include?(dep.name)
      combined = Gem::Requirement.new(gemspec_req[dep.name].as_list + dep.requirement.as_list)
      need = lowest_satisfying(dep.name, combined)
      if need && need > floor[dep.name]
        warn "  raise #{dep.name} #{floor[dep.name]} -> #{need} (required by #{n} #{floor[n]})"
        floor[dep.name] = need
        changed = true
      end
    end
  end
  break unless changed
end

File.open("Gemfile.floor", "w") do |f|
  f.puts %(source "https://rubygems.org")
  f.puts "# AUTO-GENERATED by scripts/floor_gemfile.rb — do not edit."
  direct.each { |n| f.puts %(gem "#{n}", "#{floor[n]}") }
  f.write File.read("Gemfile")[/group :development.*?^end/m].lines[1..-2].join
end

puts File.read("Gemfile.floor")
