=begin
#smplkit Logging API

#API for the smplkit logging service.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'smplkit_logging_client/api_client'
require 'smplkit_logging_client/api_error'
require 'smplkit_logging_client/api_model_base'
require 'smplkit_logging_client/version'
require 'smplkit_logging_client/configuration'

# Models
require 'smplkit_logging_client/models/error'
require 'smplkit_logging_client/models/error_response'
require 'smplkit_logging_client/models/list_meta'
require 'smplkit_logging_client/models/log_group'
require 'smplkit_logging_client/models/log_group_list_response'
require 'smplkit_logging_client/models/log_group_request'
require 'smplkit_logging_client/models/log_group_resource'
require 'smplkit_logging_client/models/log_group_response'
require 'smplkit_logging_client/models/log_level'
require 'smplkit_logging_client/models/logger'
require 'smplkit_logging_client/models/logger_bulk_item'
require 'smplkit_logging_client/models/logger_bulk_request'
require 'smplkit_logging_client/models/logger_bulk_response'
require 'smplkit_logging_client/models/logger_list_response'
require 'smplkit_logging_client/models/logger_request'
require 'smplkit_logging_client/models/logger_resource'
require 'smplkit_logging_client/models/logger_response'
require 'smplkit_logging_client/models/logger_source'
require 'smplkit_logging_client/models/logger_source_list_response'
require 'smplkit_logging_client/models/logger_source_resource'
require 'smplkit_logging_client/models/pagination_meta'
require 'smplkit_logging_client/models/service_list_response'
require 'smplkit_logging_client/models/service_resource'
require 'smplkit_logging_client/models/usage_attributes'
require 'smplkit_logging_client/models/usage_list_response'
require 'smplkit_logging_client/models/usage_resource'

# APIs
require 'smplkit_logging_client/api/log_groups_api'
require 'smplkit_logging_client/api/logger_sources_api'
require 'smplkit_logging_client/api/loggers_api'
require 'smplkit_logging_client/api/services_api'
require 'smplkit_logging_client/api/usage_api'

module SmplkitGeneratedClient::Logging
  class << self
    # Customize default settings for the SDK using block.
    #   SmplkitGeneratedClient::Logging.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
