=begin
#smplkit Flags API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SmplkitGeneratedClient::Flags::FlagSourceResource
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SmplkitGeneratedClient::Flags::FlagSourceResource do
  #let(:instance) { SmplkitGeneratedClient::Flags::FlagSourceResource.new }

  describe 'test an instance of FlagSourceResource' do
    it 'should create an instance of FlagSourceResource' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SmplkitGeneratedClient::Flags::FlagSourceResource)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["flag_source"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
