=begin
#smplkit Flags API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmplkitGeneratedClient::Flags::UsageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsageApi' do
  before do
    # run before each test
    @api_instance = SmplkitGeneratedClient::Flags::UsageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsageApi' do
    it 'should create an instance of UsageApi' do
      expect(@api_instance).to be_instance_of(SmplkitGeneratedClient::Flags::UsageApi)
    end
  end

  # unit tests for list_flags_usage
  # List Flags Usage
  # Return current resource usage counts for the authenticated account.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_period 
  # @return [UsageListResponse]
  describe 'list_flags_usage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
